import users from './users.json';
import user from './users.json';

// mock data generated by mockaroo.com
export default async function getMockData(url: string, id?: number) {
    await timeout();
    if (url.startsWith('auth/')) return { token: 'c84f18a2-c6c7-4850-be15-93f9cbaef3b3' };
    else if (url === 'users' && !id) return users;
    else if (url.startsWith('users/')) return user;
}

const delay = 200;
export function timeout(ms?: number) {
    return new Promise(resolve => setTimeout(resolve, ms || delay));
}
